# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
