# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160221_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.IntegerField()),
                ('full', models.FloatField()),
                ('empty', models.FloatField()),
            ],
        ),
    ]
