# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limits',
            name='empty',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='limits',
            name='full',
            field=models.FloatField(null=True),
        ),
    ]
